### ISSUE TITLE
Meist getippte Tipps als Barcharts

### ISSUE THREAD

**Issue by StefanWinters** [fabianallendorf/klixx-data#2]
Hey, erstmal wirklich klasse Arbeit :)

Für die Graphen der meist getippten Antworten und Verteilung der Viewzahlen empfehle ich einen Barchart = Horizontale Balken. Ich habe zuerst vermutet dass die Y-Achse bei 0 anfängt und nach rechts höher wird. Die Y Achsen Beschriftung kann man auch nicht ganz erkennen. Das ist blöd wenn es nicht linear aufwärts geht.

Daher empfehle ich ein Barchart mit dem top Tipp/Viewzahl oben. Da kommt es weniger zur Verwirrung da es so eher einer Topliste ähnelt wo der top Tipp oben ist. Ist leichter verständlich :)

**Comment by fabianallendorf** [comment]
Danke für dein Feedback. Ich verstehe was du meinst und werde es auf jeden Fall ausprobieren :+1:

**Comment by fabianallendorf** [comment]
Ist jetzt live ;)
