### ISSUE TITLE
SSL verschlüsselung

### ISSUE THREAD

**Issue by west1nat0r** [fabianallendorf/klixx-data#4]
Moin,

Ist kein Datenissue, aber HTTPS mittels SSL sollte standard sein und bei HTTP sträubt es mir die Haare. Kann gerne unterstützen :)

Kostenfreie CA:
https://letsencrypt.org/de/

**Comment by fabianallendorf** [comment]
Ja das ist ein valider Punkt den ich bisher nicht hoch priorisiert hatte, da es sich um eine (fast) statische Webseite handelt und keine Daten vom Nutzer zum Server übertragen werden. Ich verstehe allerdings, dass es ein Dorn im Auge ist.

**Comment by fabianallendorf** [comment]
https://klixx.allendorf.me/ 🥳

**Comment by west1nat0r** [comment]
Geil 😍 Props an die schnelle Umsetzung! Und an die Http zu HTTPS Umleitung gedacht :)

Wenn denn nur creepjack.de das noch umsetzen würde 😅
