### ISSUE TITLE
Datenbasis

### ISSUE THREAD

**Issue by whiletruefranz** [fabianallendorf/klixx-data#6]
Hallo!

Kein wirklicher Issue, aber eine Rückfrage:

Hast du dir alle Folgen noch mal angesehen, oder auf Basis welcher Daten hast du die ganzen Sachen ausgewertet?

Tolles Projekt!

**Comment by fabianallendorf** [comment]
Ja, ich bin durch jede Folge geskippt und habe die Tipps usw. notiert. Kannst du alles in [dieser CSV-Datei](https://github.com/fabianallendorf/klixx-data/blob/main/klixx.csv) sehen und damit arbeiten wenn du Lust hast ;)
